# Quick Regression Model on Hacker News Dataset
- Predicting upvotes by using the bag of words model with post title

In [1]:
#analytics
import pandas as pd
import numpy as np

#Natural language processing: Next we import packages to convert the json data from json file and stopwords
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

##### Reading in Our Dataset
The dataset has over 200K post titles with the respective number of likes (or number of points) and the number of comments. Since its not possible to train a dataset this huge on the local computer, we're going to have to subset the data

[dataset](https://www.kaggle.com/hacker-news/hacker-news-posts)

In [19]:
hack_data = pd.read_csv('C:/Users/Darshil/gitly/Deep-Learning/My Projects/Flask-app/project_specific/E2_predict_likes_hackernews/hn_posts.csv')
hack_data.head(10)

title  num_points  num_comments
0  You have two days to comment if you want stem ...           1             0
1                         SQLAR  the SQLite Archiver           1             0
2  What if we just printed a flatscreen televisio...           1             0
3                                  algorithmic music           1             0
4  How the Data Vault Enables the Next-Gen Data W...           1             0
5                      Saving the Hassle of Shopping           1             1
6  Macalifa  A new open-source music app for UWP ...           1             0
7  GitHub  theweavrs/Macalifa: A music player wri...           1             0
8                      Google Allo  first Impression           3             0
9      Advanced Multimedia on the Linux Command Line           1             0

In [45]:
hack_data[hack_data['num_points']>100]

title  num_points  \
67                            Appropriate Uses for SQLite         125   
88      UnGoogled Chromium: Chromium with enhanced pri...         251   
127     Designing and producing 2FA tokens to sell on ...         138   
158                            Finance is Not the Economy         237   
239                  The decline of Stack Overflow (2015)         291   
240     Bidirectional Replication is coming to Postgre...         200   
275     Bay Area wages soaring but still cant keep up ...         103   
282     Park.io  automating tasks to make $125k per month         342   
288     Game Genie declassified: That summer I played ...         156   
295                     John Carmack .plan Archive (2014)         122   
296                 Swiss endorse new surveillance powers         124   
326     How Police and Courts are Misusing Unreliable ...         104   
327                Two years spent spamming spammers back         406   
338                     The Democratization of Censorship         147   
341     Uvloop  Ultra fast implementation of asyncio e...         120   
387     Windows 10 has an undocumented certificate pin...         119   
390     Ask HN: What are the best practises for using ...         276   
401     KrebsOnSecurity is now up and hosted on Google...         230   
435     In San Francisco, a Sinking Skyscraper and a D...         125   
449          My love-hate relationship with LuaJIT (2015)         111   
481     Study Explains Why We Arrest Moms for Putting ...         166   
483     Probe of leaked U.S. NSA hacking tools examine...         109   
510                       Am I Introverted, or Just Rude?         227   
519                                  Python by the C side         131   
541                           Microservices  Please, dont         119   
542     Naval Academy to name its cyber building after...         211   
583     Bike manufacturer sees huge reduction in deliv...         544   
586     Show HN: G9.js  Automatically Interactive Diff...         215   
621                 Everybody Thinks They're Middle-Class         119   
691     First Ever Quadriplegic Treated with Stem Cell...         216   
...                                                   ...         ...   
292337              Walking Every Street in San Francisco         157   
292398                The true size of a country or state         105   
292436  Dear Dad, Send Money  Letters from Students in...         148   
292479                The Internet of Way Too Many Things         393   
292577  Bypassing the Linux kernel for high-performanc...         179   
292612  The 21-year-old building India's largest hotel...         142   
292630               Better and worse ways to spot a liar         256   
292651                                  The Pixel Factory         739   
292674           Sshmuxd: SSH proxy to replace jump hosts         108   
292696                Show HN: HTML5 version of StarCraft         320   
292716                                     Fixing Twitter         308   
292720                           The Myth of Quality Time         160   
292734  The Founder of Firefox Wrote His Own Screenpla...         223   
292736                         All Websites Look the Same         171   
292777                      Proposal for a Go Interpreter         114   
292794                        India's Forgotten Stepwells         295   
292830  Slipping Away: Jo Aubin Has  Alzheimer's. He's 38         177   
292846  Tell HN: Paywalls with workarounds are OK; pay...         176   
292870                            Random Valid US Address         143   
292892           The Hardest Places in the World to Visit         121   
292896  SICP Distilled: An idiosyncratic tour of SICP ...         243   
292910      Kubernetes from the ground up: the API server         116   
292932                                  Death to Bullshit         325   
292985  Public defender: its impossib

#### Before we extract our features we need to subset the data

In [22]:
#for now we'll take the first 1000 and then implement later. Idea: concat 700 above 100 and 300 below
df = hack_data.head(1000)

#### Extracting our features

In [23]:
"""
Now we'll apply the bag of words model on our title column bit before we do that we need to clean our data: 
- remove all stop words
- remove words with length < 4
- remove punctuations
"""

# We will now begin cleaning up our 2 columns namely "headline" and "short_description"
punctuations_list = [",", ":", ";", ".", "'", '"', "’", "?", "/", "-", "+", "&", "(", ")", "/"]
sw = stopwords.words('english')

#Here we have created a function that will clean up any given pandases series
def preprocess_textcol(name):
    df['new_{}'.format(name)] = df[name].apply(lambda x: ' '.join([word.strip() for word in x.split() if word not in (sw)
                                                                             and word.lower() not in (sw) 
                                                                             and word.upper() not in sw
                                                                             and word.title() not in (sw)
                                                                         and word not in (punctuations_list) and len(word)>4 
                                                                        and word.isdigit() == False ]))  #numbers doesnt work    
    return df['new_{}'.format(name)] 

#creating 2 new columns out of the original columns "headlines" and "short_description"
df['new_title'] = preprocess_textcol('title')

C:\Users\Darshil\Anaconda3\lib\site-packages\ipykernel\__main__.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Darshil\Anaconda3\lib\site-packages\ipykernel\__main__.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [24]:
#lets view our data
df.head(15)

title  num_points  \
0   You have two days to comment if you want stem ...           1   
1                          SQLAR  the SQLite Archiver           1   
2   What if we just printed a flatscreen televisio...           1   
3                                   algorithmic music           1   
4   How the Data Vault Enables the Next-Gen Data W...           1   
5                       Saving the Hassle of Shopping           1   
6   Macalifa  A new open-source music app for UWP ...           1   
7   GitHub  theweavrs/Macalifa: A music player wri...           1   
8                       Google Allo  first Impression           3   
9       Advanced Multimedia on the Linux Command Line           1   
10  Ask HN: What TLD do you use for local developm...           4   
11                                         Muroc Maru           1   
12            Why companies make their products worse           4   
13                              Tuning AWS SQS Queues           3   
14                              The Promise of GitHub           2   

    num_comments                                        new_title  
0              0                         comment cells classified  
1              0                            SQLAR SQLite Archiver  
2              0             printed flatscreen television boxes?  
3              0                                algorithmic music  
4              0                 Vault Enables Next-Gen Warehouse  
5              1                           Saving Hassle Shopping  
6              0                       Macalifa open-source music  
7              0  GitHub theweavrs/Macalifa: music player written  
8              0                          Google first Impression  
9              0                Advanced Multimedia Linux Command  
10             7                               local development?  
11             0                                            Muroc  
12             0                         companies products worse  
13             0                                    Tuning Queues  
14             0                                   Promise GitHub

#### Next we need to create our bag of words model and create a count vector matrix

In [14]:
data_corpus = list(df['title'])
X = vectorizer.fit_transform(data_corpus) 
print(X.toarray())
print(vectorizer.get_feature_names())

test_df = pd.DataFrame(X.toarray(), columns =vectorizer.get_feature_names() )
test_df

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['000', '01', '10', '100k', '11', '12', '125k', '16th', '17', '1778', '1959', '1967', '1978', '1979', '1985', '1993', '1996', '1997', '1999', '2000', '2003', '2007', '2008', '2009', '200mb', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '21', '285m', '29', '35a', '400', '500k', '60fps', '62', 'abruptly', 'absolutely', 'abuse', 'academy', 'accelerated', 'accelerators', 'accenture', 'access', 'accessbility', 'accessible', 'accident', 'accidentally', 'accordions', 'account', 'accounts', 'accreditor', 'acquisition', 'across', 'acting', 'action', 'actions', 'activity', 'actor', 'actors', 'actually', 'adapted', 'address', 'administrator', 'adobe', 'adresses', 'ads', 'advanced', 'advances', 'advice', 'advisory', 'affair', 'affordable', 'africa', 'african', 'agents', 'agree', 'agricultural', 'ahead', 'ai', 'aided', 'airbnb', 'aircraft', 'airlines', 'airpods', 'airpo

000  01  10  100k  11  12  125k  16th  17  1778   ...    years  yelp  \
0      0   0   0     0   0   0     0     0   0     0   ...        0     0   
1      0   0   0     0   0   0     0     0   0     0   ...        0     0   
2      0   0   0     0   0   0     0     0   0     0   ...        0     0   
3      0   0   0     0   0   0     0     0   0     0   ...        0     0   
4      0   0   0     0   0   0     0     0   0     0   ...        0     0   
5      0   0   0     0   0   0     0     0   0     0   ...        0     0   
6      0   0   0     0   0   0     0     0   0     0   ...        0     0   
7      0   0   0     0   0   0     0     0   0     0   ...        0     0   
8      0   0   0     0   0   0     0     0   0     0   ...        0     0   
9      0   0   0     0   0   0     0     0   0     0   ...        0     0   
10     0   0   0     0   0   0     0     0   0     0   ...        0     0   
11     0   0   0     0   0   0     0     0   0     0   ...        0     0   
12     0   0   0     0   0   0     0     0   0     0   ...        0     0   
13     0   0   0     0   0   0     0     0   0     0   ...        0     0   
14     0   0   0     0   0   0     0     0   0     0   ...        0     0   
15     0   0   0     0   0   0     0     0   0     0   ...        0     0   
16     0   0   0     0   0   0     0     0   0     0   ...        0     0   
17     0   0   0     0   0   0     0     0   0     0   ...        0     0   
18     0   0   0     0   0   0     0     0   0     0   ...        0     0   
19     0   0   0     0   0   0     0     0   0     0   ...        0     0   
20     0   0   0     0   0   0     0     0   0     0   ...        0     0   
21     0   0   0     0   0   0     0     0   0     0   ...        0     0   
22     0   0   0     0   0   0     0     0   0     0   ...        0     0   
23     0   0   0     0   0   0     0     0   0     0   ...        0     0   
24     0   0   0     0   0   0     0     0   0     0   ...        0     0   
25     0   0   0     0   0   0     0     0   0     0   ...        0     0   
26     0   0   0     0   0   0     0     0   0     0   ...        0     0   
27     0   0   0     0   0   0     0     0   0     0   ...        0     0   
28     0   0   0     0   0   0     0     0   0     0   ...        0     0   
29     0   0   0     0   0   0     0     0   0     0   ...        0     0   
..   ...  ..  ..   ...  ..  ..   ...   ...  ..   ...   ...      ...   ...   
970    0   0   0     0   0   0     0     0   0     0   ...        0     0   
971    0   0   0     0   0   0     0     0   0     0   ...        0     0   
972    0   0   0     0   0   0     0     0   0     0   ...        0     0   
973    0   0   0     0   0   0     0     0   0     0   ...        0     0   
974    0   0   0     0   0   0     0     0   0     0   ...        0     0   
975    0   0   0     0   0   0     0     0   0     0   ...        0     0   
976    0   0   0     0   0   0     0     0   0     0   ...        0     0   
977    0   0   0     0   0   0     0     0   0     0   ...        0     0   
978    0   0   0     0   0   0     0     0   0     0   ...        0     0   
979    0   0   0     0   0   0     0     0   0     0   ...        0     0   
980    0   0   0     0   0   0     0     0   0     0   ...        0     0   
981    0   0   0     0   0   0     0     0   0     0   ...        0     0   
982    0   0   0     0   0   0     0     0   0     0   ...        0     0   
983    0   0   0     0   0   0     0     0   0     0   ...        0     0   
984    0   0   0     0   0   0     0     0   0     0   ...        0     0   
985    0   0   0     0   0   0     0     0   0     0   ...        0     0   
986    0   0   0     0   0   0     0     0   0     0   ...        0     0   
987    0   0   0     0   0   0     0     0   0     0   ...        0     0   
988    0   0   0     0   0   0     0     0   0     0   ...        0     0   
989    0   0   0     0   0   0     0     0   0     0   ...        0     0   
9

#### Last but not the least we need to train it using scikit learn 

In [25]:
from sklearn import linear_model

#call model, fit and train
model = linear_model.LinearRegression()
model.fit(test_df,df['num_points'])


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [34]:
# Now we predict!

test_val = vectorizer.transform(['Google first Impression printed flatscreen television boxes? local development?']) 
print ('New value: ', test_val.toarray()[0])
model.predict(test_val)

New value:  [0 0 0 ... 0 0 0]


array([-22.10218896])

#### This model is horrible we will need to train it on a much larger dataset
#### Next we need to save this model to deploy 

In [39]:
from sklearn.externals import joblib
joblib.dump(model,'predict_likes_hackernews')

PermissionError: [Errno 13] Permission denied: 'C:/Users/Darshil/gitly/Deep-Learning/My Projects/Flask-app/project_specific/E2_predict_likes_hackernews'

In [ ]:
"""# Example code for count vectorization (from other project)
data_corpus = ["John likes to watch movies. Mary likes movies too.", 'darshil also likes to watch movies']
X = vectorizer.fit_transform(data_corpus) 
print(X.toarray())
print(vectorizer.get_feature_names())

test_df = pd.DataFrame(X.toarray(), columns =vectorizer.get_feature_names() )
test_df

#new values
new_val = vectorizer.transform(['hello likes to']) 
print ('New value: ', new_val.toarray()[0])"""